#**Salary Problem**

In [1]:
import pandas as pd
from sklearn import preprocessing

# from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
from google.colab import files
uploaded=files.upload()

Saving SalaryData_Train(1).csv to SalaryData_Train(1).csv

In [3]:
train=pd.read_csv('SalaryData_Train(1).csv')

In [4]:
from google.colab import files
uploaded=files.upload()

Saving SalaryData_Test(1).csv to SalaryData_Test(1).csv

In [5]:
test= pd.read_csv('SalaryData_Test(1).csv')

In [6]:
train.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
train.shape

(30161, 14)

In [8]:
train.insert(14,'Salary_cat','')

In [9]:
for i in range (0,len(train['Salary'])):
  if train['Salary'][i]==' <=50K':
    train['Salary_cat'][i]='0'
  else:
      train['Salary_cat'][i]='1'

<ipython-input-9-2017f4dffd77>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Salary_cat'][i]='0'
<ipython-input-9-2017f4dffd77>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Salary_cat'][i]='1'

In [10]:
label_encoder=preprocessing.LabelEncoder()
train['workclass']=label_encoder.fit_transform(train['workclass'])
train['maritalstatus']=label_encoder.fit_transform(train['maritalstatus'])
train['occupation']=label_encoder.fit_transform(train['occupation'])
train['relationship']=label_encoder.fit_transform(train['relationship'])
train['race']=label_encoder.fit_transform(train['race'])
train['sex']=label_encoder.fit_transform(train['sex'])
train['native']=label_encoder.fit_transform(train['native'])

In [11]:
train.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary,Salary_cat
0,39,5,Bachelors,13,4,0,1,4,1,2174,0,40,37,<=50K,0
1,50,4,Bachelors,13,2,3,0,4,1,0,0,13,37,<=50K,0
2,38,2,HS-grad,9,0,5,1,4,1,0,0,40,37,<=50K,0
3,53,2,11th,7,2,5,0,2,1,0,0,40,37,<=50K,0
4,28,2,Bachelors,13,2,9,5,2,0,0,0,40,4,<=50K,0

In [12]:
train=train.drop(['education','Salary'],axis=1)

In [13]:
train.shape

(30161, 13)

test

In [14]:
test.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K

In [15]:
test.insert(14,'Salary_cat','')

In [16]:
for i in range (0,len(test['Salary'])):
  if test['Salary'][i]==' <=50K':
    test['Salary_cat'][i]='0'
  else:
      test['Salary_cat'][i]='1'

<ipython-input-16-26f91376608f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Salary_cat'][i]='0'
<ipython-input-16-26f91376608f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Salary_cat'][i]='1'

In [17]:
label_encoder=preprocessing.LabelEncoder()
test['workclass']=label_encoder.fit_transform(test['workclass'])
test['maritalstatus']=label_encoder.fit_transform(test['maritalstatus'])
test['occupation']=label_encoder.fit_transform(test['occupation'])
test['relationship']=label_encoder.fit_transform(test['relationship'])
test['race']=label_encoder.fit_transform(test['race'])
test['sex']=label_encoder.fit_transform(test['sex'])
test['native']=label_encoder.fit_transform(test['native'])

In [18]:
test.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary,Salary_cat
0,25,2,11th,7,4,6,3,2,1,0,0,40,37,<=50K,0
1,38,2,HS-grad,9,2,4,0,4,1,0,0,50,37,<=50K,0
2,28,1,Assoc-acdm,12,2,10,0,4,1,0,0,40,37,>50K,1
3,44,2,Some-college,10,2,6,0,2,1,7688,0,40,37,>50K,1
4,34,2,10th,6,4,7,1,4,1,0,0,30,37,<=50K,0

In [19]:
test=test.drop(['education','Salary'],axis=1)

In [20]:
test.head()

,age,workclass,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary_cat
0,25,2,7,4,6,3,2,1,0,0,40,37,0
1,38,2,9,2,4,0,4,1,0,0,50,37,0
2,28,1,12,2,10,0,4,1,0,0,40,37,1
3,44,2,10,2,6,0,2,1,7688,0,40,37,1
4,34,2,6,4,7,1,4,1,0,0,30,37,0

In [21]:
test.shape

(15060, 13)

In [22]:
x=train.iloc[:,:-1]
y=train['Salary_cat']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

In [24]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((21112, 12), (21112,), (9049, 12), (9049,))

In [ ]:
clf = SVC()
param_grid = [{'kernel':['linear','relu'],'gamma':[0.5,0.1],'C':[10,0.1] }]
gsv = RandomizedSearchCV(clf,param_grid,cv=10,verbose=300)
gsv.fit(X_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_search.py:292: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 10 folds for each of 8 candidates, totalling 80 fits
[CV 1/10; 1/8] START C=10, gamma=0.5, kernel=linear.............................

In [ ]:
gsv.best_params_ , gsv.best_score_

In [ ]:
clf = SVC(kernel='linear',C=10)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

In [ ]:
X=test.iloc[:,0:-1]
Y=test['Salary_cat']

In [ ]:
y_newpred = clf.predict(X)
newacc = accuracy_score(Y, y_newpred) * 100
print("Accuracy =", newacc)
confusion_matrix(Y, y_newpred)

#**Forest Fire Problem**

In [ ]:
import pandas as pd
from sklearn import preprocessing

# from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving forestfires.csv to forestfires.csv

In [ ]:
frst=pd.read_csv('forestfires.csv')

In [ ]:
frst.head()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small

In [ ]:
frst.columns

Index(['month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind',
       'rain', 'area', 'dayfri', 'daymon', 'daysat', 'daysun', 'daythu',
       'daytue', 'daywed', 'monthapr', 'monthaug', 'monthdec', 'monthfeb',
       'monthjan', 'monthjul', 'monthjun', 'monthmar', 'monthmay', 'monthnov',
       'monthoct', 'monthsep', 'size_category'],
      dtype='object')

In [ ]:
frst=frst.drop(['month','day'],axis=1)

In [ ]:
label_encoder=preprocessing.LabelEncoder()
frst['size_category']=label_encoder.fit_transform(frst['size_category'])

In [ ]:
frst.head()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1,...,0,0,0,0,1,0,0,0,0,1
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,1
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,1
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1,...,0,0,0,0,1,0,0,0,0,1
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,0,...,0,0,0,0,1,0,0,0,0,1

In [ ]:
frst['size_category'].value_counts()

1    378
0    139
Name: size_category, dtype: int64

In [ ]:
frst.shape

(517, 29)

In [ ]:
X=frst.iloc[:,0:28]
Y=frst.iloc[:,28]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((361, 28), (361,), (156, 28), (156,))

In [ ]:
clf = SVC()
param_grid = [{'kernel':['linear','rbf'],'gamma':[0.5,0.1,0.01],'C':[10,0.1,0.001,0.0001] }]
gsv = RandomizedSearchCV(clf,param_grid,cv=10,verbose=300)
gsv.fit(X_train,y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
[CV 1/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 1/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.757 total time=   0.0s
[CV 2/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 2/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 3/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 3/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.750 total time=   0.0s
[CV 4/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 4/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 5/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 5/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 6/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 6/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 7/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 7/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 8/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 8/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.750 total time=   0.0s
[CV 9/10; 1/10] START C=10, gamma=0.5, kernel=rbf...............................
[CV 9/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.750 total time=   0.0s
[CV 10/10; 1/10] START C=10, gamma=0.5, kernel=rbf..............................
[CV 10/10; 1/10] END C=10, gamma=0.5, kernel=rbf;, score=0.750 total time=   0.0s
[CV 1/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 1/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.730 total time=   0.0s
[CV 2/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 2/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 3/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 3/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 4/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 4/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 5/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 5/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 6/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 6/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 7/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 7/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 8/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 8/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 9/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf..........................
[CV 9/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 10/10; 2/10] START C=0.0001, gamma=0.01, kernel=rbf.........................
[CV 10/10; 2/10] END C=0.0001, gamma=0.01, kernel=rbf;, score=0.750 total time=   0.0s
[CV 1/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 1/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=0.946 total time=   0.0s
[CV 2/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 2/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 3/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=0.944 total time=   0.0s
[CV 4/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 4/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=0.972 total time=   0.0s
[CV 5/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 5/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=0.917 total time=   0.0s
[CV 6/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 6/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=0.944 total time=   0.0s
[CV 7/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 7/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 8/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 8/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=0.944 total time=   0.0s
[CV 9/10; 3/10] START C=0.001, gamma=0.1, kernel=linear.........................
[CV 9/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=0.944 total time=   0.0s
[CV 10/10; 3/10] START C=0.001, gamma=0.1, kernel=linear........................
[CV 10/10; 3/10] END C=0.001, gamma=0.1, kernel=linear;, score=0.972 total time=   0.0s
[CV 1/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 1/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.865 total time=   0.0s
[CV 2/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 2/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.833 total time=   0.0s
[CV 3/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 3/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.806 total time=   0.0s
[CV 4/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 4/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.806 total time=   0.0s
[CV 5/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 5/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.861 total time=   0.0s
[CV 6/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 6/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.861 total time=   0.0s
[CV 7/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 7/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.889 total time=   0.0s
[CV 8/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 8/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.833 total time=   0.0s
[CV 9/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear........................
[CV 9/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.833 total time=   0.0s
[CV 10/10; 4/10] START C=0.0001, gamma=0.1, kernel=linear.......................
[CV 10/10; 4/10] END C=0.0001, gamma=0.1, kernel=linear;, score=0.833 total time=   0.0s
[CV 1/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 1/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.730 total time=   0.0s
[CV 2/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 2/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 3/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 3/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 4/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 4/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 5/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 5/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 6/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 6/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 7/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 7/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 8/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 8/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 9/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf...........................
[CV 9/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.722 total time=   0.0s
[CV 10/10; 5/10] START C=0.001, gamma=0.01, kernel=rbf..........................
[CV 10/10; 5/10] END C=0.001, gamma=0.01, kernel=rbf;, score=0.750 total time=   0.0s
[CV 1/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 1/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.865 total time=   0.0s
[CV 2/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 2/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.833 total time=   0.0s
[CV 3/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 3/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.806 total time=   0.0s
[CV 4/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 4/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.806 total time=   0.0s
[CV 5/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 5/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.861 total time=   0.0s
[CV 6/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 6/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.861 total time=   0.0s
[CV 7/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 7/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.889 total time=   0.0s
[CV 8/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 8/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.833 total time=   0.0s
[CV 9/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear........................
[CV 9/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.833 total time=   0.0s
[CV 10/10; 6/10] START C=0.0001, gamma=0.5, kernel=linear.......................
[CV 10/10; 6/10] END C=0.0001, gamma=0.5, kernel=linear;, score=0.833 total time=   0.0s
[CV 1/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 1/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.730 total time=   0.0s
[CV 2/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 2/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 3/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 3/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 4/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 4/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 5/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 5/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 6/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 6/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 7/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 7/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 8/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 8/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 9/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf...........................
[CV 9/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.722 total time=   0.0s
[CV 10/10; 7/10] START C=0.0001, gamma=0.5, kernel=rbf..........................
[CV 10/10; 7/10] END C=0.0001, gamma=0.5, kernel=rbf;, score=0.750 total time=   0.0s
[CV 1/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 1/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=0.946 total time=   0.1s
[CV 2/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 2/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=1.000 total time=   0.1s
[CV 3/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 3/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=0.972 total time=   0.0s
[CV 4/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 4/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=0.944 total time=   0.0s
[CV 5/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 5/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=1.000 total time=   0.1s
[CV 6/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 6/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=1.000 total time=   0.0s
[CV 7/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 7/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=0.972 total time=   0.0s
[CV 8/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 8/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=1.000 total time=   0.0s
[CV 9/10; 8/10] START C=0.1, gamma=0.5, kernel=linear...........................
[CV 9/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=0.972 total time=   0.0s
[CV 10/10; 8/10] START C=0.1, gamma=0.5, kernel=linear..........................
[CV 10/10; 8/10] END C=0.1, gamma=0.5, kernel=linear;, score=1.000 total time=   0.0s
[CV 1/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 1/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=0.946 total time=   0.1s
[CV 2/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 2/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.1s
[CV 3/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 3/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=0.972 total time=   0.0s
[CV 4/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 4/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=0.944 total time=   0.0s
[CV 5/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 5/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.1s
[CV 6/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 6/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 7/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 7/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=0.972 total time=   0.0s
[CV 8/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 8/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 9/10; 9/10] START C=0.1, gamma=0.1, kernel=linear...........................
[CV 9/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=0.972 total time=   0.0s
[CV 10/10; 9/10] START C=0.1, gamma=0.1, kernel=linear..........................
[CV 10/10; 9/10] END C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 1/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 1/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.730 total time=   0.0s
[CV 2/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 2/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.722 total time=   0.0s
[CV 3/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 3/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.722 total time=   0.0s
[CV 4/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 4/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.722 total time=   0.0s
[CV 5/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 5/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.722 total time=   0.0s
[CV 6/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 6/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.722 total time=   0.0s
[CV 7/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 7/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.722 total time=   0.0s
[CV 8/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 8/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.722 total time=   0.0s
[CV 9/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf..........................
[CV 9/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.722 total time=   0.0s
[CV 10/10; 10/10] START C=0.0001, gamma=0.1, kernel=rbf.........................
[CV 10/10; 10/10] END C=0.0001, gamma=0.1, kernel=rbf;, score=0.750 total time=   0.0s

RandomizedSearchCV(cv=10, estimator=SVC(),
                   param_distributions=[{'C': [10, 0.1, 0.001, 0.0001],
                                         'gamma': [0.5, 0.1, 0.01],
                                         'kernel': ['linear', 'rbf']}],
                   verbose=300)

In [ ]:
gsv.best_params_ , gsv.best_score_

({'kernel': 'linear', 'gamma': 0.5, 'C': 0.1}, 0.9807057057057056)

In [ ]:
clf = SVC(kernel='linear',C=10)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 100.0

array([[ 40,   0],
       [  0, 116]])